<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE feed [
        <!ELEMENT feed (id|updated|category|title|link|author|generator|openSearch:totalResults|openSearch:startIndex|openSearch:itemsPerPage|entry)*>
        <!ATTLIST feed
                xmlns CDATA #REQUIRED
                xmlns:openSearch CDATA #REQUIRED
                xmlns:gbs CDATA #REQUIRED
                xmlns:dc CDATA #REQUIRED
                xmlns:batch CDATA #REQUIRED
                xmlns:gd CDATA #REQUIRED>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT updated (#PCDATA)>
        <!ELEMENT category (#PCDATA)>
        <!ATTLIST category
                scheme CDATA #REQUIRED
                term CDATA #REQUIRED>
        <!ELEMENT title (#PCDATA)>
        <!ATTLIST title
                type CDATA #REQUIRED>
        <!ELEMENT link (#PCDATA)>
        <!ATTLIST link
                href CDATA #REQUIRED
                rel CDATA #REQUIRED
                type CDATA #REQUIRED>
        <!ELEMENT author (name|uri)*>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT uri (#PCDATA)>
        <!ELEMENT generator (#PCDATA)>
        <!ATTLIST generator
                version CDATA #REQUIRED>
        <!ELEMENT openSearch:totalResults (#PCDATA)>
        <!ELEMENT openSearch:startIndex (#PCDATA)>
        <!ELEMENT openSearch:itemsPerPage (#PCDATA)>
        <!ELEMENT entry (id|updated|category|title|link|gbs:contentVersion|gbs:embeddability|gbs:openAccess|gbs:viewability|dc:creator|dc:date|dc:description|dc:format|dc:identifier|dc:language|dc:title)*>
        <!ELEMENT gbs:contentVersion (#PCDATA)>
        <!ELEMENT gbs:embeddability (#PCDATA)>
        <!ATTLIST gbs:embeddability
                value CDATA #REQUIRED>
        <!ELEMENT gbs:openAccess (#PCDATA)>
        <!ATTLIST gbs:openAccess
                value CDATA #REQUIRED>
        <!ELEMENT gbs:viewability (#PCDATA)>
        <!ATTLIST gbs:viewability
                value CDATA #REQUIRED>
        <!ELEMENT dc:creator (#PCDATA)>
        <!ELEMENT dc:date (#PCDATA)>
        <!ELEMENT dc:description (#PCDATA)>
        <!ELEMENT dc:format (#PCDATA)>
        <!ELEMENT dc:identifier (#PCDATA)>
        <!ELEMENT dc:language (#PCDATA)>
        <!ELEMENT dc:title (#PCDATA)>
        ]>
<feed xmlns='http://www.w3.org/2005/Atom' xmlns:openSearch='http://a9.com/-/spec/opensearchrss/1.0/' xmlns:gbs='http://schemas.google.com/books/2008' xmlns:dc='http://purl.org/dc/terms' xmlns:batch='http://schemas.google.com/gdata/batch' xmlns:gd='http://schemas.google.com/g/2005'>
    <id>http://www.google.com/books/feeds/volumes</id>
    <updated>2013-03-07T09:29:15.000Z</updated>
    <category scheme='http://schemas.google.com/g/2005#kind' term='http://schemas.google.com/books/2008#volume'/>
    <title type='text'>Search results for 8024739178</title>
    <link rel='alternate' type='text/html' href='http://www.google.com'/>
    <link rel='http://schemas.google.com/g/2005#feed' type='application/atom+xml' href='http://www.google.com/books/feeds/volumes'/>
    <link rel='self' type='application/atom+xml' href='http://www.google.com/books/feeds/volumes?q=8024739178'/>
    <author>
        <name>Google Books Search</name>
        <uri>http://www.google.com</uri>
    </author>
    <generator version='beta'>Google Book Search data API</generator>
    <openSearch:totalResults>1</openSearch:totalResults>
    <openSearch:startIndex>1</openSearch:startIndex>
    <openSearch:itemsPerPage>1</openSearch:itemsPerPage>
    <entry>
        <id>http://www.google.com/books/feeds/volumes/BcGnhvX7w5EC</id>
        <updated>2013-03-07T09:29:15.000Z</updated>
        <category scheme='http://schemas.google.com/g/2005#kind' term='http://schemas.google.com/books/2008#volume'/>
        <title type='text'>Jazyky C a C++ - kompletní kapesní průvodce – 2., aktualizované vydání</title>
        <link rel='http://schemas.google.com/books/2008/thumbnail' type='image/x-unknown' href='http://bks2.books.google.com/books?id=BcGnhvX7w5EC&amp;printsec=frontcover&amp;img=1&amp;zoom=5&amp;edge=curl&amp;source=gbs_gdata'/>
        <link rel='http://schemas.google.com/books/2008/info' type='text/html' href='http://books.google.com/books?id=BcGnhvX7w5EC&amp;dq=8024739178&amp;ie=ISO-8859-1&amp;source=gbs_gdata'/>
        <link rel='http://schemas.google.com/books/2008/preview' type='text/html' href='http://books.google.com/books?id=BcGnhvX7w5EC&amp;pg=PA108&amp;dq=8024739178&amp;ie=ISO-8859-1&amp;cd=1&amp;source=gbs_gdata'/>
        <link rel='http://schemas.google.com/books/2008/annotation' type='application/atom+xml' href='http://www.google.com/books/feeds/users/me/volumes'/>
        <link rel='alternate' type='text/html' href='http://books.google.com/books?id=BcGnhvX7w5EC&amp;dq=8024739178&amp;ie=ISO-8859-1'/>
        <link rel='self' type='application/atom+xml' href='http://www.google.com/books/feeds/volumes/BcGnhvX7w5EC'/>
        <gbs:contentVersion>preview-1.0.0</gbs:contentVersion>
        <gbs:embeddability value='http://schemas.google.com/books/2008#embeddable'/>
        <gbs:openAccess value='http://schemas.google.com/books/2008#disabled'/>
        <gbs:viewability value='http://schemas.google.com/books/2008#view_partial'/>
        <dc:creator>Virius Miroslav</dc:creator>
        <dc:date>2011</dc:date>
        <dc:description>Virius Miroslav. ❚ Je-li v deklaraci lokální automatické proměnné uvedena inicializace, proběhne tato ini- cializace při každém vytvoření této proměnné, tj. při každém vstupu do bloku, který tuto deklaraci obsahuje (přesněji při každém ...</dc:description>
        <dc:format>367 pages</dc:format>
        <dc:format>book</dc:format>
        <dc:identifier>BcGnhvX7w5EC</dc:identifier>
        <dc:identifier>ISBN:8024739178</dc:identifier>
        <dc:identifier>ISBN:9788024739175</dc:identifier>
        <dc:language>cs</dc:language>
        <dc:title>Jazyky C a C++ - kompletní kapesní průvodce – 2., aktualizované vydání</dc:title>
    </entry>
</feed>